# Generated by Django 5.2.6 on 2025-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareHelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='descricao_curta',
            field=models.TextField(default='descricao_curta', help_text='Descrição resumida da instituição'),
            preserve_default=False,
        ),
    ]
