# Generated by Django 5.2.6 on 2025-09-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareHelp', '0002_instituicao_descricao_curta'),
        ('shareHelp', '0003_auto_20250922_1801'),
    ]

    operations = [
    ]
